-- 문제1 사원 번호와 사원명과 부서명과 부서의 위치를 출력하는 뷰(VIEW_LOC)를 작성하라.
DROP VIEW VIEW_LOC;
CREATE VIEW VIEW_LOC
AS
SELECT E.EMPLOYEE_ID AS "사원 번호", E.FIRST_NAME AS 사원명, DEPARTMENT_ID AS 부서명,
LOCATION_ID AS "부서의 위치" FROM EMPLOYEES E INNER JOIN DEPARTMENTS D USING(DEPARTMENT_ID);
SELECT * FROM VIEW_LOC; 

-- 문제2 30번 부서 소속 사원의 이름과 입사일과 부서명을 출력하는 뷰(VIEW_DEPT30)를 작성하라.
DROP VIEW VIEW_DEPT30;
CREATE VIEW VIEW_DEPT30
AS
SELECT  E.FIRST_NAME AS 이름, HIRE_DATE AS 입사일, D.DEPARTMENT_NAME AS 부서명
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D USING(DEPARTMENT_ID)
WHERE DEPARTMENT_ID = 30;
SELECT * FROM VIEW_DEPT30; 

-- 문제3 부서별 최대 급여 정보를 가지는 뷰(VIEW_DEPT_MAXSAL)를 생성하라
DROP VIEW VIEW_DEPT_MAXSAL;
CREATE VIEW VIEW_DEPT_MAXSAL
AS
SELECT DEPARTMENT_ID AS 부서아이디, MAX(E.SALARY) AS "최대 급여"
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D USING(DEPARTMENT_ID)
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;
SELECT * FROM VIEW_DEPT_MAXSAL; 

-- 문제4 급여를 많이 받는 순서대로 3명만 출력하는 뷰(VIEW_SAL_TOP3)와 인라인 뷰로 작성하라.
DROP VIEW VIEW_SAL_TOP3;
CREATE VIEW VIEW_SAL_TOP3
AS
SELECT EMPLOYEE_ID AS "사원 번호", FIRST_NAME AS 사원명, SALARY AS 급여
FROM(SELECT * FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM <= 3;
SELECT * FROM VIEW_SAL_TOP3;