-- [문제1] EMPLOYEES 테이블에 등록된 총사원의 수와 급여의 합, 급여의 평균을 변수에 대입하여 출력하여보자.
DECLARE
    TOTAL NUMBER;
    SUM_SALARY NUMBER;
    AVG_SALARY NUMBER;
BEGIN
    SELECT COUNT(*) INTO TOTAL FROM EMPLOYEES; 
    SELECT SUM(SALARY) INTO SUM_SALARY FROM EMPLOYEES;
    SELECT ROUND(AVG(SALARY),2) INTO AVG_SALARY FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE('총사원의 수 : ' || TOTAL);
    DBMS_OUTPUT.PUT_LINE('급여의 합 : ' || SUM_SALARY);
    DBMS_OUTPUT.PUT_LINE('급여의 평균 : ' || AVG_SALARY);
END;
/

-- [문제2] Clara 사원의 직무, 급여, 입사일자, 커미션, 부서명을 변수에 대입하여 출력하여 보자.
DECLARE
    EMP_RECORD EMPLOYEES%ROWTYPE;
    DEP_RECORD DEPARTMENTS%ROWTYPE;
    DEP_ID NUMBER;
BEGIN
    SELECT DEPARTMENT_ID INTO DEP_ID FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'CLARA';
    SELECT * INTO EMP_RECORD FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'CLARA';
    SELECT * INTO DEP_RECORD FROM DEPARTMENTS WHERE DEPARTMENT_ID = DEP_ID;
    DBMS_OUTPUT.PUT_LINE('직무 : ' || EMP_RECORD.JOB_ID);
    DBMS_OUTPUT.PUT_LINE('급여 : ' || EMP_RECORD.SALARY);
    DBMS_OUTPUT.PUT_LINE('입사날짜 : ' || EMP_RECORD.HIRE_DATE);
    DBMS_OUTPUT.PUT_LINE('커미션 : ' || EMP_RECORD.COMMISSION_PCT);
    DBMS_OUTPUT.PUT_LINE('부서명 : ' || DEP_RECORD.DEPARTMENT_NAME);
END;
/
