-- <문제1> EMPLOYEES 테이블의 모든 내용 출력
SELECT * FROM EMPLOYEES;

-- <문제2> 사원의 이름과 급여와 입사일자 만을 출력하는 SQL문을 작성해보자.
-- 힌트: 사원 정보가 저장된 테이블은 EMPLOYEES이고, 사원이름 칼럼은 FRIST_NAME, LAST_NAME과,
-- 급여 컬럼은 SALARY, 입사날자 칼럼은 HIRE_DATE이다.
SELECT FIRST_NAME, LAST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES;

-- <문제3> 직원들이 어떤 부서에 소속되어 있는지 소속 부서번호(DEPARTMENT_ID) 출력하되 중복되지 않고
-- 한번씩 출력하는 쿼리문을 작성하자.
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

-- <문제4> EMPLOYEES 테이블에서 부서번호가 110번인 직원에 관한 모든 정보만 출력하라.
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 110;

-- <문제5> EMPLOYEES 테이블에서 급여가 5000미만이 되는 직원에 정보 중에서 사번과 이름, 급여를 출력하라.
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES WHERE SALARY < 5000;

-- <문제6> 이름이 John인 사람의 직원번호와 직원명과 직급을 출력하라.
SELECT EMPLOYEE_ID, FIRST_NAME,JOB_ID FROM EMPLOYEES WHERE FIRST_NAME = 'John';

-- <문제7> 급여가 5000에서 10000이하 직원 정보 출력
SELECT * FROM EMPLOYEES WHERE 5000 <= SALARY AND SALARY <= 10000;
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 5000 AND 10000;

-- <문제8> 직원번호가 134이거나 201이거나 107인 직원 정보 출력
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 134 OR EMPLOYEE_ID = 201 OR EMPLOYEE_ID = 107;
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID in(107, 134, 201);

-- <문제9> 직급이 FI_MGR가 아닌 직원
SELECT * FROM EMPLOYEES WHERE NOT JOB_ID = 'FI_MGR';
SELECT * FROM EMPLOYEES WHERE JOB_ID != 'FI_MGR';

-- <문제10> 급여가 2500에서 4500까지의 범위에 속한 직원의 직원번호, 이름, 급여를 출력하라.
-- (AND 연산자와 BETWEEN AND 연산자 사용 두개모두 사용해서 보여줄 것)
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES 
WHERE 2500 <= SALARY  AND SALARY <= 4500;
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES 
WHERE SALARY BETWEEN 2500 AND 4500;

-- <문제11> 커미션비율이 0.3 이거나 0.05 이거나 0.1 중의 하나인 직원의 직원번호, 이름, 급여,
-- 커미션 비율을 출력하라. (OR 연산자와 IN 연산자 모두 사용 해볼 것)
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES 
WHERE COMMISSION_PCT = 0.3 OR COMMISSION_PCT = 0.05 OR COMMISSION_PCT = 0.1;
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES 
WHERE COMMISSION_PCT IN(0.3, 0.05, 0.1);

-- <문제12> 이름에 a를 포함하지 않은 직원의 직원번호, 이름을 출력하라.
SELECT EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES WHERE NOT FIRST_NAME LIKE '%a%'
AND NOT FIRST_NAME LIKE 'A%'; 

-- <문제13> 자신의 직속상관이 없는 직원의 전체 이름과 직급과 직원번호를 출력하라.
SELECT FIRST_NAME, LAST_NAME, JOB_ID, EMPLOYEE_ID FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

-- <문제14> 직원번호, 이름, 급여를 급여가 높은 순으로 출력하라.
SELECT  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
ORDER BY SALARY DESC; 

-- <문제15> 입사일이 가장 최근인 직원 순으로 직원번호, 이름, 입사일을 출력하라.
SELECT  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE FROM EMPLOYEES
ORDER BY HIRE_DATE DESC; 