-- <문제1> 이미 존재하는 EMP01 테이블에 입사일 칼럼(CREDATE)을 날짜형으로 추가하라.
DESC EMP01;
ALTER TABLE EMP01 ADD CREDATE DATE;

-- <실습1> 고객 테이블 생성을 위한 필드 설정
DROP TABLE TB_CUSTOMER;
CREATE TABLE TB_CUSTOMER(
    CUSTOMER_CD CHAR(7),
    CUSTOMER_NM VARCHAR2(20) NOT NULL,
    MW_FLG CHAR(1) NOT NULL,
    BIRTH_DAY CHAR(8) NOT NULL,
    PHONE_NUMBER VARCHAR2(16),
    EMAIL VARCHAR2(30),
    TOTAL_POINT NUMBER(10) DEFAULT 0,
    REG_DTTM CHAR(14)
);
-- 제약조건
ALTER TABLE TB_CUSTOMER ADD CONSTRAINT TB_CUSTOMER_PK PRIMARY KEY(CUSTOMER_CD);
ALTER TABLE TB_CUSTOMER ADD CONSTRAINT TB_CUSTOMER_CK CHECK(MW_FLG IN('M','W'));
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TB_CUSTOMER';

-- <실습2> 학생 성적 테이블을 만들어 봅시다.
DROP TABLE STUDENT_SCORE;
CREATE TABLE STUDENT_SCORE(
    STUDENT_NO NUMBER(10),
    STUDENT_NAME CHAR(5) NOT NULL,
    STUDENT_KOR NUMBER(3) DEFAULT 0 NOT NULL,
    STUDENT_ENG NUMBER(3) DEFAULT 0 NOT NULL,
    STUDENT_MATH NUMBER(3) DEFAULT 0 NOT NULL,
    STUDENT_TOTAL NUMBER(3) DEFAULT 0 NOT NULL,
    STUDENT_AVG NUMBER(3) DEFAULT 0 NOT NULL,
    DEPARTMENT_CORE CHAR(3)
);
DESC STUDENT_SCORE;
-- 제약 조건
ALTER TABLE STUDENT_SCORE ADD CONSTRAINT STUDENT_SCORE_PK PRIMARY KEY(STUDENT_NO);
ALTER TABLE STUDENT_SCORE ADD CONSTRAINT STUDENT_SCORE_FK FOREIGN KEY(DEPARTMENT_CORE)
REFERENCES DEPARTMENTS2(DEPARTMENT_CORE);
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'STUDENT_SCORE';
-- 데이터 삽입
INSERT INTO STUDENT_SCORE VALUES('1', 'KHR', 100, 80, 90, 270, 90, '001');
INSERT INTO STUDENT_SCORE VALUES('2', 'HGD', 80, 80, 80, 240, 80, '003');
INSERT INTO STUDENT_SCORE VALUES('3', 'KSY', 100, 100, 100, 300, 100, '002');
SELECT * FROM STUDENT_SCORE;
TRUNCATE TABLE STUDENT_SCORE;
-- <실습3> 학과 테이블을 만든다.
DROP TABLE DEPARTMENTS2;
CREATE TABLE DEPARTMENTS2(
    DEPARTMENT_CORE CHAR(3),
    DEPARTMENT_NAME VARCHAR2(20) NOT NULL
);
-- 제약 조건
ALTER TABLE DEPARTMENTS2 ADD CONSTRAINT DEPARTMENTS2_PK PRIMARY KEY(DEPARTMENT_CORE);
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEPARTMENTS2';
-- 데이터 삽입
INSERT INTO DEPARTMENTS2 VALUES('001','컴퓨터공학과');
INSERT INTO DEPARTMENTS2 VALUES('002','IT응용보안과');
INSERT INTO DEPARTMENTS2 VALUES('003','웹디자인과');
SELECT * FROM DEPARTMENTS2;