-- 오라클과 자바연동 테스팅
SELECT FIRST_NAME, SALARY FROM EMPLOYEES; 

DROP TABLE BOOKS;
CREATE TABLE BOOKS ( 
    BOOK_ID NUMBER(4), 
    TITLE VARCHAR2(50), 
    PUBLISHER VARCHAR2(30), 
    YEAR VARCHAR2(10), 
    PRICE NUMBER(6), 
    PRIMARY KEY(BOOK_ID) 
); 
 
CREATE SEQUENCE BOOK_SEQ 
START WITH 1 
INCREMENT BY 1 ; 
 
INSERT INTO BOOKS VALUES (BOOK_SEQ.nextval, 'Operating System Concepts', 'Wiley', '2003',30700); 
INSERT INTO BOOKS VALUES (BOOK_SEQ.nextval, 'Head First PHP and MYSQL', 'OReilly', '2009', 58000); 
INSERT INTO BOOKS VALUES (BOOK_SEQ.nextval, 'C Programming Language', 'Prentice-Hall', '1989', 35000); 
INSERT INTO BOOKS VALUES (BOOK_SEQ.nextval, 'Head First SQL', 'OReilly', '2007', 43000); 
ROLLBACK;
COMMIT;
SELECT * FROM BOOKS;

-- DOG 테이블 연동
DROP TABLE DOG;
CREATE TABLE DOG ( 
    DOG_ID NUMBER(4), 
    DOG_NAME VARCHAR2(50), 
    DOG_AGE NUMBER(4), 
    DOG_BIRTH VARCHAR2(10)
); 
ALTER TABLE DOG ADD CONSTRAINT DOG_PK PRIMARY KEY(DOG_ID);
DROP SEQUENCE DOG_SEQ;
CREATE SEQUENCE DOG_SEQ 
START WITH 1 
INCREMENT BY 1 ; 
INSERT INTO DOG VALUES (DOG_SEQ.nextval, '콩이', 5, '2021'); 
INSERT INTO DOG VALUES (DOG_SEQ.nextval, '깜순이', 2, '2024'); 
INSERT INTO DOG VALUES (DOG_SEQ.nextval, '밥풀', 8, '2018'); 
INSERT INTO DOG VALUES (DOG_SEQ.nextval, '흰둥이', 6, '2020'); 
SELECT * FROM DOG;
ROLLBACK;
COMMIT;
UPDATE DOG set DOG_NAME = '콩콩이', DOG_AGE = 5, DOG_BIRTH = '2021' WHERE DOG_ID = 1;