-- user security table
DROP TABLE USERS;
CREATE TABLE USERS ( 
    USERNAME VARCHAR2(50), 
    PASSWORD VARCHAR2(50) NOT NULL, 
    ENABLED CHAR(1) DEFAULT '1'
); 
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY(USERNAME);

DROP TABLE AUTHORITIES;
CREATE TABLE AUTHORITIES ( 
    USERNAME VARCHAR2(50) NOT NULL, 
    AUTHORITY VARCHAR2(50) NOT NULL 
); 
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_USERNAME_FK 
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME); 

CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME, AUTHORITY); 
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('user00','123456'); 
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('member00','123456'); 
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('admin00','123456'); 
 
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('user00','ROLE_USER'); 
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('member00','ROLE_MEMBER'); 
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin00','ROLE_MEMBER'); 
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin00','ROLE_ADMIN'); 
COMMIT; 
SELECT * FROM USERS;
SELECT * FROM AUTHORITIES;

-- mybatis security table
DROP TABLE SECURITYMEMBER;
CREATE TABLE SECURITYMEMBER ( 
    NO NUMBER, 
    ID VARCHAR2(50) NOT NULL, 
    PW VARCHAR2(100) NOT NULL, 
    NAME VARCHAR2(100) NOT NULL, 
    COIN NUMBER(10)DEFAULT 0, 
    REG_DATE DATE DEFAULT SYSDATE, 
    UPD_DATE DATE DEFAULT SYSDATE, 
    ENABLED CHAR(1) DEFAULT '1'
); 
ALTER TABLE SECURITYMEMBER ADD CONSTRAINT SECURITYMEMBER_PK PRIMARY KEY(NO);

CREATE TABLE SECURITYMEMBER_AUTH ( 
    NO NUMBER NOT NULL, 
    AUTH VARCHAR2(50) NOT NULL 
); 
 
ALTER TABLE SECURITYMEMBER_AUTH ADD CONSTRAINT SECURITYMEMBER_AUTH_FK 
FOREIGN KEY (NO) REFERENCES SECURITYMEMBER(NO);

CREATE SEQUENCE SECURITYMEMBER_SEQ 
START WITH 1 
INCREMENT BY 1;
--user_id: member0  user_pw: pwd0  user_id: member1  user_pw: pwd1 
INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES 
(SECURITYMEMBER_SEQ.NEXTVAL, 
'member0','$2a$10$ohA1zfwg.el0qEbcUisAtOwfEM/Q0XikaQqzLF4RLvvlQBHjNhkUG','회원 0'); 
INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES 
(SECURITYMEMBER_SEQ.NEXTVAL, 
'member1','$2a$10$0YeNJZi0ZpHNJ962vF4KbOPbiiAW/FWaIOu8PTypWyzKnqmHDXEbe','회원 1'); 
INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES 
(SECURITYMEMBER_SEQ.NEXTVAL, 
'member2','$2a$10$q8SAiCddta4vsxze3klZKOWWLoo1qwgwTQ7MdBcN3ZV8oL435vszm','회원 2'); 
INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES 
(SECURITYMEMBER_SEQ.NEXTVAL, 
'admin3','$2a$10$tu7hm6.6uYkcvMi//ol9A.gLeyGFwezZmtlSnvgUeBhgZ1UaSN1CG','관리자 3'); 
INSERT INTO SECURITYMEMBER(NO, ID, PW, NAME) VALUES 
(SECURITYMEMBER_SEQ.NEXTVAL, 
'admin4','$2a$10$SAipGDDRGkCStRyrao.pPeseuMoeBFiifUH0RAFDyyb.p/WG59zuS','관리자 4'); 
 
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES (
(SELECT NO FROM SECURITYMEMBER WHERE ID = 'member0'),'ROLE_MEMBER'); 
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER 
WHERE ID = 'member1'),'ROLE_MEMBER'); 
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER 
WHERE ID = 'member2'),'ROLE_MEMBER'); 
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER 
WHERE ID = 'admin3'),'ROLE_ADMIN'); 
INSERT INTO SECURITYMEMBER_AUTH (NO, AUTH) VALUES ((SELECT NO FROM SECURITYMEMBER 
WHERE ID = 'admin4'),'ROLE_ADMIN'); 
 
COMMIT; 
SELECT * FROM SECURITYMEMBER;
SELECT * FROM SECURITYMEMBER_AUTH;