-- 1. Sales 부서 소속 사원의 이름과 입사일을 출력하라.
SELECT E.FIRST_NAME AS "사원의 이름", E.HIRE_DATE AS 입사일, D.DEPARTMENT_NAME AS 부서명 
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID WHERE D.DEPARTMENT_NAME = 'Sales';

-- 2. 커미션을 받는 직원의 이름과 그가 속한 부서명을 출력하라.

SELECT E.FIRST_NAME AS "직원의 이름", E.COMMISSION_PCT AS 커미션, D.DEPARTMENT_NAME AS 부서명 
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID WHERE E.COMMISSION_PCT IS NOT NULL;

-- 3. Guy와 동일한 부서에서 근무하는 직원의 이름과 부서번호를 출력하라.
SELECT FIRST_NAME AS "직원의 이름", DEPARTMENT_ID AS 부서번호
FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID 
FROM EMPLOYEES WHERE FIRST_NAME = 'Guy');






