-- 1. 학과테이블을 생성한다.(subject) 
DROP TABLE SUBJECT;
CREATE TABLE SUBJECT(
    NO NUMBER,
    S_NUM CHAR(2) NOT NULL,
    S_NAME VARCHAR2(30) NOT NULL
);
ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_PK PRIMARY KEY(NO);
INSERT INTO SUBJECT VALUES(1, '01', '컴퓨터학과');
INSERT INTO SUBJECT VALUES(2, '02', '교육학과');
INSERT INTO SUBJECT VALUES(3, '03', '신문방송학과');
INSERT INTO SUBJECT VALUES(4, '04', '인터넷비즈니스과');
INSERT INTO SUBJECT VALUES(5, '05', '기술경영과');
SELECT * FROM SUBJECT;

-- 2. 학생테이블을 생성한다.(student) 
CREATE TABLE STUDENT (
    NO NUMBER,
    SD_NUM CHAR(8) NOT NULL,
    SD_NAME VARCHAR2(50) NOT NULL,
    SD_ID VARCHAR2(30) NOT NULL,
    SD_PASSWD VARCHAR2(30) NOT NULL,
    S_NUM CHAR(2) NOT NULL,
    SD_JUMIN CHAR(13) NOT NULL,
    SD_PHONE VARCHAR2(20) NOT NULL,
    SD_ADDRESS VARCHAR2(100) NOT NULL,
    SD_EMAIL VARCHAR2(100) NOT NULL,
    SD_DATE DATE NOT NULL
);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY(NO);
SELECT * FROM STUDENT;
-- 3. 과목테이블을 생성한다.(lesson)  
CREATE TABLE LESSON(
    NO NUMBER,
    L_NUM VARCHAR2(5) NOT NULL,
    L_NAME VARCHAR(50) NOT NULL
);
ALTER TABLE LESSON ADD CONSTRAINT LESSON_PK PRIMARY KEY(NO);
INSERT INTO LESSON VALUES (1, 'K', '국어');
INSERT INTO LESSON VALUES (2, 'M', '수학');
INSERT INTO LESSON VALUES (3, 'E', '영어');
INSERT INTO LESSON VALUES (4, 'H', '역사');
INSERT INTO LESSON VALUES (5, 'P', '프로그래밍');
INSERT INTO LESSON VALUES (6, 'D', '데이터베이스');
INSERT INTO LESSON VALUES (7, 'ED', '교육학이론');
SELECT * FROM LESSON;

-- 4. 수강테이블을 생성한다.(trainee) 
CREATE TABLE TRAINEE(
    NO NUMBER,
    SD_NUM CHAR(8) NOT NULL,
    L_NUM VARCHAR2(5) NOT NULL,
    T_SECTION VARCHAR2(10) NOT NULL,
    T_DATE DATE  NOT NULL
);
ALTER TABLE TRAINEE ADD CONSTRAINT TRAINEE_PK PRIMARY KEY(NO);
ALTER TABLE TRAINEE ADD CONSTRAINT TPAINEE_CK 
CHECK(T_SECTION IN('CULTURE', 'MAJOR','MINOR'));