-- FUNCTION 프로그램 작성 부서번호값을 입력하면, DEP01 부서번호를 참조해서 부서명을 리턴해주는 함수를 작성하시오.
-- 해당된 부서번호가 없다면 '해당 부서 번호가 없음'을 리턴해주세요.
CREATE OR REPLACE FUNCTION GET_DEPART_NAME(VDEPT_NO IN EMPLOYEES.DEPARTMENT_ID%TYPE) RETURN VARCHAR2
IS
    VCOUNT NUMBER := 0;
    VDEPARTMENT_NAME VARCHAR2(100);
BEGIN
    SELECT COUNT(*) INTO VCOUNT FROM DEPARTMENTS WHERE DEPARTMENT_ID = VDEPT_NO;
    IF VCOUNT = 0 THEN
        VDEPARTMENT_NAME := '해당부서없음';
    ELSE
        SELECT DEPARTMENT_NAME INTO VDEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = VDEPT_NO;
    END IF;
    RETURN VDEPARTMENT_NAME;
END;
/
SELECT FIRST_NAME, JOB_ID, SALARY, DEPARTMENT_ID, 
GET_DEPART_NAME(DEPARTMENT_ID) AS "부서명" 
FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'STEVEN';
SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'STEVEN';

SELECT GET_DEPART_NAME(10) FROM DUAL;
SELECT COUNT(*) FROM DEPARTMENTS WHERE DEPARTMENT_ID = 300;

VARIABLE VDNAME VARCHAR2;
EXECUTE :VDNAME := GET_DEPART_NAME(20);
PRINT VDNAME;

-- 부서번호를 함수매개변수로 등록하여 해당부서의 평균 급여를 리턴하는 함수를 작성하시오.
CREATE OR REPLACE FUNCTION GET_AGE_SALARY(VDEPT_NO IN EMPLOYEES.DEPARTMENT_ID%TYPE) RETURN VARCHAR2
IS
    VAVG_SALARY VARCHAR2(100);
BEGIN
    SELECT TO_CHAR(AVG(SALARY), '999,999,999') INTO VAVG_SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = VDEPT_NO;
    RETURN VAVG_SALARY;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        VAVG_SALARY :=  '해당부서없음';
        RETURN VAVG_SALARY;
END;
/
SELECT GET_AGE_SALARY(300) FROM DUAL;
SELECT FIRST_NAME, JOB_ID, SALARY, DEPARTMENT_ID, GET_DEPART_NAME(DEPARTMENT_ID) AS "부서명" , 
GET_AGE_SALARY(DEPARTMENT_ID) AS "부서명 평균월급"
FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'STEVEN';
