-- 회원관리 테이블
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    NO NUMBER,
    ID VARCHAR2(30) NOT NULL check(regexp_like(ID,'^[가-힣a-zA-Z0-9]{3,10}$')),
    PW VARCHAR2(30) NOT NULL check(regexp_like(PW,'^[a-zA-Z0-9]{3,10}$')),
    NAME VARCHAR2(20) NULL check(regexp_like(NAME,'^[가-힣a-zA-Z0-9]{3,10}$'))
);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(NO);
-- Member 시퀀스 생성
DROP SEQUENCE Member_SEQ;
CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, ?, ?, ?);
UPDATE MEMBER SET ID = ?, PW = ?, NAME = ? WHERE NO = ?;
SELECT * FROM MEMBER WHERE NO > 0 ORDER BY NO DESC;
SELECT * FROM MEMBER WHERE NO = ?;
DELETE FROM MEMBER WHERE NO = ?;

-- Member query(curd)
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'abcd', '1234', '홍길동');
UPDATE MEMBER SET ID = '1212', PW = 'qwe', NAME = '가나다' WHERE NO = 1;
SELECT * FROM MEMBER WHERE NO > 0 ORDER BY NO DESC;
SELECT * FROM MEMBER WHERE NO = 1;
DELETE FROM MEMBER WHERE NO = 1;