-- 학과 테이블
CREATE TABLE SUBJECT( 
    NO NUMBER NOT NULL,         -- 일련번호
    NUM VARCHAR2(2) NOT NULL,   -- 학과번호
    NAME VARCHAR2(24) NOT NULL, -- 학과명
    PRIMARY KEY(NO), 
    UNIQUE(NUM)
);
CREATE SEQUENCE SUBJECT_SEQ
START WITH 1
INCREMENT BY 1;

-- 과목 테이블
CREATE TABLE LESSON( 
    NO NUMBER NOT NULL,         -- 일련번호
    ABBRE VARCHAR2(2) NOT NULL, -- 과목약어
    NAME VARCHAR2(20) NOT NULL, -- 과목명
    PRIMARY KEY(NO),
    UNIQUE(ABBRE)
);
CREATE SEQUENCE LESSON_SEQ 
START WITH 1
INCREMENT BY 1;

-- 학생 테이블
CREATE TABLE STUDENT( 
    NO NUMBER NOT NULL,
    NUM VARCHAR2(8) NOT NULL,
    NAME VARCHAR2(12) NOT NULL,
    ID VARCHAR2(12) NOT NULL,
    PASSWD VARCHAR2(12) NOT NULL,
    SUBJECT_NUM VARCHAR2(2) NOT NULL,
    BIRTHDAY VARCHAR2(8) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    ADDRESS VARCHAR2(80) NOT NULL,
    EMAIL VARCHAR2(40) NOT NULL,
    REGISTER_DATE DATE DEFAULT SYSDATE
);
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_PK PRIMARY KEY(NO);
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_NUM_UK UNIQUE(NUM);
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_ID_UK UNIQUE(ID);
ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_SUBJECT_FK FOREIGN KEY(SUBJECT_NUM)
REFERENCES SUBJECT(NUM) ON DELETE SET NULL;

CREATE SEQUENCE STUDENT_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'STUDENT';
SELECT * FROM STUDENT;
SELECT LPAD(COUNT(*)+1,4,'0') AS STUDENT_COUNT FROM STUDENT WHERE SUBJECT_NUM = '01';

SELECT * FROM SUBJECT;